before_script: []
stages: [
  "build",
]

documentation:
  image: "timnn/texlive"
  stage: "build"
  script: [
      "cd documentation",
      "pdflatex Main.tex"
      ]
  artifacts:
    paths:
      - documentation/Main.pdf
